# Generated by Django 5.1.3 on 2025-01-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RoomEscapeInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "branch",
                    models.CharField(max_length=30, null=True, verbose_name="지점"),
                ),
                ("title", models.TextField(null=True, verbose_name="이름")),
                (
                    "image_url",
                    models.CharField(max_length=1, null=True, verbose_name="이미지"),
                ),
                (
                    "genre",
                    models.CharField(max_length=1, null=True, verbose_name="장르"),
                ),
                (
                    "time",
                    models.CharField(max_length=10, null=True, verbose_name="이용시간"),
                ),
                (
                    "difficulty",
                    models.CharField(max_length=10, null=True, verbose_name="난이도"),
                ),
                (
                    "horror",
                    models.CharField(max_length=30, null=True, verbose_name="공포도"),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=10, null=True, verbose_name="세부 설명"
                    ),
                ),
                (
                    "booking_link",
                    models.CharField(
                        max_length=10, null=True, verbose_name="예약 링크"
                    ),
                ),
            ],
        ),
    ]
