name: 이슈 템플릿
description: 이슈 작성 시 아래 항목을 따라 작성해주세요.
title: "[TYPE]: 제목을 입력하세요"
labels: []
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ❗️ 이슈 제목은 아래의 형식을 맞춰주세요 
        - [FEAT] : 기능 추가
        - [FIX] : 에러 수정, 버그 수정
        - [CHORE] : gradle 세팅, 위의 것 이외에 거의 모든 것
        - [DOCS] : README, 문서
        - [REFACTOR] : 코드 리팩토링 (기능 변경 없이 코드만 수정할 때)
        - [MODIFY] : 코드 수정 (기능의 변화가 있을 때)

  - type: textarea
    id: issue-content
    attributes:
      label: "✨ 이슈 내용"
      description: "이슈 내용을 자세히 설명해주세요."
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: "✅ 체크리스트"
      options:
        - label: "Assignees / Labels / Milestone 선택"
        - label: "이슈가 적절한지 확인"
        - label: "관련 문서나 코드 리뷰 필요 여부 확인"
